### ISSUE TITLE
How to control the returned file path from shebang tool

### ISSUE THREAD

**Issue by asmwarrior** [matveyt/shebang#2]
Hi, first, this project is quite nice, thanks for your work!

I have one issue when I try to use this tool to generate wxWidgets' build options, see my post here:

[The shebang command to run the bash script under Windows CMD](https://forums.codeblocks.org/index.php/topic,24634.msg168096.html#msg168096)

One issue is that under Windows, I would like the return path has normal Windows style, such as:

`-IF:/msys2/mingw64/lib/wx/include/msw-unicode-3.1`

In my post in the Code::Blocks forum.

Any ideas?

Thanks.

**Comment by matveyt** [comment]
Hello,
You need to have `mingw64\bin` in your `$PATH` before `msys2\usr\bin` (and possibly other MSYS2/Cygwin directories).
To explain what's happening: here output format depends on the value of environment variable `$MSYSTEM` (cf. MSYS2 shell vs. MINGW64 shell). Shebang sets it up for you with respect to your `$PATH`. Therefore, the order is important.

**Comment by asmwarrior** [comment]
> 
> 
> Hello,
> You need to have `mingw64\bin` in your `$PATH` before `msys2\usr\bin` (and possibly other MSYS2/Cygwin directories).
> To explain what's happening: here output format depends on the value of environment variable `$MSYSTEM` (cf. MSYS2 shell vs. MINGW64 shell). Shebang sets it up for you with respect to your `$PATH`. Therefore, the order is important.

Hi, many thanks,  this did solve my issue.

I think I will close this ticket.
